### PR TITLE
Zaman123

### PR DESCRIPTION
**Pull request by zamanrahimi**
Ticket zaman123 is finalized by zaman!

### CODE REVIEW

**Review by WalizadaShoaib — CHANGES_REQUESTED** [review]
Mr. Rahimi your code does not meet our shop requirements, please bring these changes 

1
3
4
5

Regards 
Shoaib

**Comment by zamanrahimi** [comment]
> Mr. Rahimi your code does not meet our shop requirements, please bring these changes
> 
> 1
> 3
> 4
> 5
> 
> Regards
> Shoaib

------------------------------
Dear Walizada sb, 

Please upload all the files. I have test it. it is working properly.

**Review by WalizadaShoaib — CHANGES_REQUESTED** [review]
Dear Rahimi Sb,

your code has to be changed. (line no 15)

Regards,

**Comment by zamanrahimi** [comment]
The second changes are done!

**Review by WalizadaShoaib — APPROVED** [review]
Excellent job.
Line 15 is working properly.

**Comment by zamanrahimi** [comment]
@zamanrahimi 

From now onwards its upto you.

**Comment by zamanrahimi** [comment]
@taqihedayat 

now up to you

**Review by WalizadaShoaib — CHANGES_REQUESTED** [review]
There are few issues with your code.

Regards,
Supervisor

**Comment by zamanrahimi** [comment]
Dear Stage Manager, 

Line 16 is added. 

Best,
Zaman

**Review by WalizadaShoaib — APPROVED** [review]

**Review by WalizadaShoaib — APPROVED** [review]
good job.

**Review by WalizadaShoaib — APPROVED** [review]
great job

**Comment by WalizadaShoaib** [comment]
@taqihedayat 

please

**Review by taqihedayat — APPROVED** [review]
afasdf

**Pull request merged**
